=== jtojnar/wrcq/result/results.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="results">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="team" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="member" maxOccurs="5" minOccurs="1"><!-- 5 is for legacy reasons see http://wrcq.rogaining.cz/standard/results/0.1#member -->
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="firstname" use="required" />
											<xs:attribute type="xs:string" name="lastname" use="required" />
											<xs:attribute name="country" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:pattern value="AFG|ALB|ALG|AND|ANG|ANT|ARG|ARM|ARU|ASA|AUS|AUT|AZE|BAH|BAN|BAR|BDI|BEL|BEN|BER|BHU|BIH|BIZ|BLR|BOL|BOT|BRA|BRN|BRU|BUL|BUR|CAF|CAM|CAN|CAY|CGO|CHA|CHI|CHN|CIV|CMR|COD|COK|COL|COM|CPV|CRC|CRO|CUB|CYP|CZE|DEN|DJI|DMA|DOM|ECU|EGY|ERI|ESA|ESP|EST|ETH|FIJ|FIN|FRA|FSM|GAB|GAM|GBR|GBS|GEO|GEQ|GER|GHA|GRE|GRN|GUA|GUI|GUM|GUY|HAI|HKG|HON|HUN|INA|IND|IRI|IRL|IRQ|ISL|ISR|ISV|ITA|IVB|JAM|JOR|JPN|KAZ|KEN|KGZ|KIR|KOR|KSA|KUW|LAO|LAT|LBA|LBR|LCA|LES|LIB|LIE|LTU|LUX|MAD|MAR|MAS|MAW|MDA|MDV|MEX|MGL|MHL|MKD|MLI|MLT|MNE|MON|MOZ|MRI|MTN|MYA|NAM|NCA|NED|NEP|NGR|NIG|NOR|NRU|NZL|OMA|PAK|PAN|PAR|PER|PHI|PLE|PLW|PNG|POL|POR|PRK|PUR|QAT|ROU|RSA|RUS|RWA|SAM|SEN|SEY|SIN|SKN|SLE|SLO|SMR|SOL|SOM|SRB|SRI|STP|SUD|SUI|SUR|SVK|SWE|SWZ|SYR|TAN|TGA|THA|TJK|TKM|TLS|TOG|TPE|TRI|TUN|TUR|TUV|UAE|UGA|UKR|URU|USA|UZB|VAN|VEN|VIE|VIN|YEM|ZAM|ZIM|XXX" />
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:integer" name="id" use="required" />
						<xs:attribute type="xs:string" name="name" />
						<xs:attribute type="xs:integer" name="score" use="required" />
						<xs:attribute name="time" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="[0-9]{1,2}:[0-5][0-9]:[0-5][0-9]" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute type="xs:integer" name="penalty" use="required" />
						<xs:attribute name="duration" default="24">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:maxInclusive value="24" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="gender" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="men" />
									<xs:enumeration value="mixed" />
									<xs:enumeration value="women" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="age" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="open" />
									<xs:enumeration value="veteran" />
									<xs:enumeration value="superveteran" />
									<xs:enumeration value="ultraveteran" />
									<xs:enumeration value="junior" />
									<xs:enumeration value="under18" />
									<xs:enumeration value="under20" />
									<xs:enumeration value="under23" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="status" default="finished">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="not started" />
									<xs:enumeration value="not finished" />
									<xs:enumeration value="overtime" />
									<xs:enumeration value="disqualified" />
									<xs:enumeration value="out of competition" />
									<xs:enumeration value="finished" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jtojnar/wrcq/result/narc2011.xml
<results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="results.xsd">
	<team id="15" score="3430" time="20:32:00" penalty="0" gender="men" age="open" duration="24">
		<member firstname="Eric" lastname="Bone" country="USA" />
		<member firstname="Dennis" lastname="Wilkinson" country="USA" />
	</team>
	<team id="9" score="2980" time="23:41:25" penalty="0" gender="mixed" age="open" duration="24">
		<member firstname="Louise" lastname="Oram" country="USA" />
		<member firstname="Christoph" lastname="Rufenacht" country="USA" />
	</team>
	<team id="7" score="2930" time="23:31:57" penalty="0" gender="women" age="veteran" duration="24">
		<member firstname="Pam" lastname="James" country="USA" />
		<member firstname="Catherine" lastname="Hagan" country="USA" />
	</team>
	<team id="24" score="2930" time="23:40:11" penalty="0" gender="men" age="superveteran" duration="24">
		<member firstname="Bryan" lastname="Chubb" country="USA" />
		<member firstname="Leo" lastname="Rankin" country="USA" />
	</team>
	<team id="2" score="2920" time="23:08:18" penalty="0" gender="mixed" age="open" duration="24">
		<member firstname="James" lastname="Heilman" country="CAN" />
		<member firstname="Wakana" lastname="Heilman" country="CAN" />
	</team>
	<team id="3" score="2640" time="23:37:54" penalty="0" gender="men" age="veteran" duration="24">
		<member firstname="Tom De" lastname="Vries" country="USA" />
		<member firstname="Geraint" lastname="Edmunds" country="USA" />
	</team>
	<team id="23" score="2440" time="18:22:26" penalty="0" gender="men" age="veteran" duration="24">
		<member firstname="Kevin" lastname="Matrosovs" country="USA" />
		<member firstname="Dan" lastname="Crockett" country="USA" />
	</team>
	<team id="10" score="2390" time="23:39:49" penalty="0" gender="men" age="superveteran" duration="24">
		<member firstname="Chris" lastname="Oram" country="USA" />
		<member firstname="John" lastname="Harbuck" country="USA" />
	</team>
	<team id="18" score="2350" time="23:56:12" penalty="0" gender="mixed" age="open" duration="24">
		<member firstname="Angela" lastname="Forseille" country="USA" />
		<member firstname="Jean-Michel" lastname="Lessard" country="USA" />
	</team>
	<team id="8" score="2200" time="23:47:27" penalty="0" gender="men" age="superveteran" duration="24">
		<member firstname="John" lastname="Rance" country="USA" />
		<member firstname="Bruce" lastname="Rennie" country="USA" />
	</team>
	<team id="1" score="2160" time="23:23:34" penalty="0" gender="men" age="superveteran" duration="24">
		<member firstname="Bud" lastname="Laird" country="USA" />
		<member firstname="Glen" lastname="Brake" country="USA" />
	</team>
	<team id="11" score="2110" time="23:45:31" penalty="0" gender="women" age="superveteran" duration="24">
		<member firstname="Marion" lastname="Owen" country="USA" />
		<member firstname="Althea" lastname="Shaw" country="USA" />
	</team>
	<team id="4" score="2040" time="23:18:56" penalty="0" gender="women" age="superveteran" duration="24">
		<member firstname="Margo" lastname="Mactaggart" country="USA" />
		<member firstname="Kathryn" lastname="Mueller" country="USA" />
	</team>
	<team id="17" score="1930" time="22:30:35" penalty="0" gender="men" age="open" duration="24">
		<member firstname="Wade" lastname="Tokarek" country="USA" />
		<member firstname="Dana" lastname="Manhard" country="USA" />
	</team>
	<team id="19" score="1820" time="23:45:59" penalty="0" gender="men" age="open" duration="24">
		<member firstname="Jame" lastname="Mollison" country="USA" />
		<member firstname="Adrian" lastname="Low" country="USA" />
	</team>
	<team id="27" score="1780" time="23:51:12" penalty="0" gender="women" age="veteran" duration="24">
		<member firstname="Charlottee" lastname="MacNaughton" country="USA" />
		<member firstname="Andree" lastname="Powers" country="USA" />
	</team>
	<team id="5" score="1760" time="23:16:46" penalty="0" gender="mixed" age="superveteran" duration="24">
		<member firstname="Eric" lastname="Smith" country="USA" />
		<member firstname="Mary" lastname="Smith" country="USA" />
	</team>
	<team id="26" score="1600" time="20:19:17" penalty="0" gender="mixed" age="open" duration="24">
		<member firstname="Scott" lastname="Covey" country="USA" />
		<member firstname="Tyler" lastname="Dwyer" country="USA" />
		<member firstname="Sara" lastname="Bucovaz" country="USA" />
	</team>
	<team id="21" score="1460" time="23:57:39" penalty="0" gender="mixed" age="open" duration="24">
		<member firstname="Tori" lastname="Owen" country="USA" />
		<member firstname="Jared" lastname="Kesteven" country="USA" />
	</team>
	<team id="20" score="1390" time="22:22:59" penalty="0" gender="mixed" age="open" duration="24">
		<member firstname="Tammy" lastname="Howe" country="USA" />
		<member firstname="Daryl" lastname="Spencer" country="USA" />
	</team>
	<team id="25" score="1370" time="18:07:34" penalty="0" gender="mixed" age="veteran" duration="24">
		<member firstname="Mikhail" lastname="Pekour" country="USA" />
		<member firstname="Svetlana" lastname="Sergueeva" country="USA" />
	</team>
	<team id="14" score="1360" time="16:15:45" penalty="0" gender="men" age="open" duration="24">
		<member firstname="Duncan" lastname="Coo" country="USA" />
		<member firstname="Tom" lastname="Crack" country="USA" />
	</team>
	<team id="16" score="1030" time="23:48:13" penalty="0" gender="women" age="superveteran" duration="24">
		<member firstname="Karen" lastname="Lachance" country="XXX" />
		<member firstname="Robyn" lastname="Rennie" country="XXX" />
	</team>
	<team id="13" score="860" time="17:02:10" penalty="0" gender="mixed" age="open" duration="24">
		<member firstname="Patrick" lastname="Gottsacker" country="USA" />
		<member firstname="Jinnet" lastname="Powel" country="USA" />
	</team>
	<team id="12" score="270" time="23:41:44" penalty="0" gender="mixed" age="superveteran" duration="24">
		<member firstname="Bob" lastname="Reddick" country="USA" />
		<member firstname="Pat" lastname="Reddick" country="USA" />
		<member firstname="Ken" lastname="Lew" country="USA" />
	</team>
	<team id="22" score="1650" time="23:48:04" penalty="0" gender="mixed" age="superveteran">
		<member firstname="Hilary" lastname="Anderson" country="CAN" />
		<member firstname="Michel" lastname="Roberge" country="CAN" />
	</team>
</results>

=== jtojnar/wrcq/result/ukrc2012.xml
<results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="results.xsd">
	<team id="1" score="213" time="22:55:29" penalty="0" gender="men" age="open" name="Yaremcha">
		<member firstname="Vasiliy" lastname="Stefurak" country="UKR" />
		<member firstname="Vasiliy" lastname="Bondarchuk" country="UKR" />
		<member firstname="Petro" lastname="Polkovnikov" country="UKR" />
	</team>
	<team id="2" score="212" time="23:24:52" penalty="0" gender="men" age="open" name="Machnovcy">
		<member firstname="Sergiy" lastname="Yaroshenko" country="UKR" />
		<member firstname="Sergiy" lastname="Sirinyuk" country="UKR" />
	</team>
	<team id="3" score="212" time="23:53:36" penalty="0" gender="men" age="open" name="Krym">
		<member firstname="Taras" lastname="Konyukhov" country="UKR" />
		<member firstname="Oleksandr" lastname="Sheshukov" country="UKR" />
	</team>
	<team id="4" score="180" time="21:43:55" penalty="0" gender="men" age="junior" name="??lush_1">
		<member firstname="Sergiy" lastname="Mospan" country="UKR" />
		<member firstname="Mikola" lastname="Kovbasyuk" country="UKR" />
	</team>
	<team id="5" score="178" time="23:24:11" penalty="0" gender="men" age="open" name="Inter SSM-2">
		<member firstname="Oleksandr" lastname="Buligin" country="UKR" />
		<member firstname="Sergiy" lastname="Vasilkov" country="UKR" />
	</team>
	<team id="6" score="174" time="22:18:25" penalty="0" gender="men" age="open" name="Inter SSM-1">
		<member firstname="Pavlo" lastname="Buligin" country="UKR" />
		<member firstname="Mikhailo" lastname="Arsenyuk" country="UKR" />
	</team>
	<team id="7" score="171" time="22:14:03" penalty="0" gender="men" age="junior" name="??lush_2">
		<member firstname="Volodimir" lastname="Zyatik" country="UKR" />
		<member firstname="Andriy" lastname="Gudz" country="UKR" />
	</team>
	<team id="8" score="154" time="23:53:59" penalty="0" gender="men" age="open" name="MIDIZ_1">
		<member firstname="Oleksandr" lastname="Mikhailov" country="UKR" />
		<member firstname="Viktor" lastname="Mikhailov" country="UKR" />
	</team>
	<team id="9" score="149" time="22:57:22" penalty="0" gender="men" age="superveteran" name="Aksakali">
		<member firstname="Valeriy" lastname="Shulga" country="UKR" />
		<member firstname="Tanasiy" lastname="Makoviytchuk" country="UKR" />
	</team>
	<team id="10" score="133" time="20:14:00" penalty="0" gender="men" age="open" name="Meridian">
		<member firstname="Volodimir" lastname="Lkpulyak" country="UKR" />
		<member firstname="Dmitro" lastname="Sandul" country="UKR" />
		<member firstname="Igor" lastname="Zerya" country="UKR" />
	</team>
	<team id="11" score="132" time="23:17:08" penalty="0" gender="men" age="open" name="Gold Star">
		<member firstname="Mikola" lastname="Bazarov" country="UKR" />
		<member firstname="Dmitro" lastname="Kisakov" country="UKR" />
	</team>
	<team id="12" score="130" time="23:02:53" penalty="0" gender="men" age="junior" name="Vinnicija-1">
		<member firstname="Dmitro" lastname="Kozel" country="UKR" />
		<member firstname="Sergiy" lastname="Nagornyuk" country="UKR" />
		<member firstname="Roman" lastname="Simonishin" country="UKR" />
	</team>
	<team id="13" score="111" time="22:55:28" penalty="0" gender="men" age="open" name="Migovo">
		<member firstname="Dmitro" lastname="Olievskiy" country="UKR" />
		<member firstname="Ruslan" lastname="Oliyevskiy" country="UKR" />
	</team>
	<team id="14" score="80" time="10:49:50" penalty="0" gender="men" age="veteran" name="Atrerium">
		<member firstname="Mikola" lastname="Kovaltchuk" country="UKR" />
		<member firstname="Sergiy" lastname="Sur" country="UKR" />
	</team>
	<team id="15" score="79" time="13:46:11" penalty="0" gender="men" age="junior" name="Maximum-2">
		<member firstname="Sergiy" lastname="Brilinskiy" country="UKR" />
		<member firstname="Bogdan" lastname="Kobelyanskiy" country="UKR" />
	</team>
	<team id="16" score="67" time="22:59:00" penalty="0" gender="men" age="junior" name="CHIP">
		<member firstname="Ivan" lastname="Khrapko" country="UKR" />
		<member firstname="Dmitro" lastname="Poburian" country="UKR" />
	</team>
	<team id="17" score="47" time="6:39:46" penalty="0" gender="men" age="junior" name="Maximum-3">
		<member firstname="XXX" lastname="Novoselcev" country="UKR" />
		<member firstname="XXX" lastname="Rokhmanov" country="UKR" />
	</team>
	<team id="18" score="38" time="8:06:54" penalty="0" gender="men" age="junior" name="Mandriki">
		<member firstname="Andriy" lastname="Kelya" country="UKR" />
		<member firstname="Vyacheslav" lastname="Kelya" country="UKR" />
	</team>
	<team id="19" score="35" time="21:20:10" penalty="0" gender="men" age="junior" name="2?">
		<member firstname="Vitaliy" lastname="Karamishev" country="UKR" />
		<member firstname="Ilya" lastname="Motryuk" country="UKR" />
	</team>
	<team id="20" score="26" time="7:10:08" penalty="0" gender="men" age="open" name="Migovo2">
		<member firstname="Oleksandr" lastname="Voloshin" country="UKR" />
		<member firstname="Maksim" lastname="Kurishev" country="UKR" />
	</team>
	<team id="21" score="155" time="20:25:06" penalty="0" gender="men" age="open" name="Nutrend">
		<member firstname="Ruslan" lastname="Shimtchuk" country="UKR" />
		<member firstname="Vyacheslav" lastname="Shimtchuk" country="UKR" />
	</team>
	<team id="22" score="165" time="24:21:33" penalty="0" gender="men" age="open" name="Maximum-1">
		<member firstname="Georgiy" lastname="Fetcho" country="UKR" />
	</team>
	<team id="23" score="80" time="25:38:25" penalty="0" gender="men" age="open" name="">
		<member firstname="Andriy" lastname="Bilce" country="UKR" />
	</team>
	<team id="24" score="181" time="23:14:14" penalty="0" gender="mixed" age="junior" name="Vinnicija_4">
		<member firstname="Polina" lastname="Zakharova" country="UKR" />
		<member firstname="Volodymyr" lastname="Bezditniy" country="UKR" />
	</team>
	<team id="25" score="172" time="23:27:21" penalty="0" gender="mixed" age="open" name="Vinnicija_5">
		<member firstname="Oleksandr" lastname="Marchuk" country="UKR" />
		<member firstname="Bogdan" lastname="Grelya" country="UKR" />
		<member firstname="Lena" lastname="Mironenko" country="UKR" />
	</team>
	<team id="26" score="164" time="22:44:13" penalty="0" gender="mixed" age="junior" name="MIDIZ_2">
		<member firstname="Vyacheslav" lastname="Demtchenko" country="UKR" />
		<member firstname="Yuriy" lastname="Richlo" country="UKR" />
		<member firstname="Anna Polina" lastname="Ivantchak" country="UKR" />
		<member firstname="Vadim" lastname="Chomenko" country="UKR" />
	</team>
	<team id="27" score="145" time="21:51:02" penalty="0" gender="mixed" age="open" name="Lviv">
		<member firstname="Andriy" lastname="Tkatch" country="UKR" />
		<member firstname="Christina" lastname="Ustyanovska" country="UKR" />
	</team>
	<team id="28" score="80" time="23:30:52" penalty="0" gender="mixed" age="superveteran" name="Alchevskije mandrivniki">
		<member firstname="Yuriy" lastname="Shur" country="UKR" />
		<member firstname="Tetyana" lastname="Dritova" country="UKR" />
	</team>
	<team id="29" score="70" time="20:40:01" penalty="0" gender="mixed" age="open" name="Kharkiv-2">
		<member firstname="Dmitro" lastname="Kovriga" country="UKR" />
		<member firstname="Karolina" lastname="Shpartina" country="UKR" />
	</team>
	<team id="30" score="51" time="8:57:33" penalty="0" gender="mixed" age="open" name="Kharkiv-4">
		<member firstname="XXX" lastname="Svyatishinko" country="UKR" />
		<member firstname="Ira" lastname="Glushko" country="UKR" />
	</team>
	<team id="31" score="43" time="5:52:26" penalty="0" gender="mixed" age="junior" name="Vinnicija-3">
		<member firstname="Oleksandr" lastname="Kovalinskiy" country="UKR" />
		<member firstname="Anastasia" lastname="Basyuk" country="UKR" />
	</team>
	<team id="32" score="168" time="23:40:04" penalty="0" gender="women" age="open" name="Vinnicija-2">
		<member firstname="Lyudmila" lastname="Yaremenko" country="UKR" />
		<member firstname="Olga" lastname="Mazur" country="UKR" />
	</team>
	<team id="33" score="147" time="23:58:54" penalty="0" gender="women" age="open" name="Leader">
		<member firstname="Yulia" lastname="Soroka" country="UKR" />
		<member firstname="Natalia" lastname="Troyanovska" country="UKR" />
	</team>
	<team id="34" score="120" time="22:24:10" penalty="0" gender="women" age="junior" name="Shvidkist">
		<member firstname="Natalia" lastname="Shelepyuk" country="UKR" />
		<member firstname="Maria" lastname="Sokolovska" country="UKR" />
	</team>
	<team id="35" score="84" time="23:15:59" penalty="0" gender="women" age="veteran" name="Osvitjani">
		<member firstname="Antonina" lastname="Tumak" country="UKR" />
		<member firstname="Valentina" lastname="Bevzo" country="UKR" />
	</team>
	<team id="36" score="25" time="8:21:50" penalty="0" gender="women" age="junior" name="Targani">
		<member firstname="Anastasia" lastname="Chistyakova" country="UKR" />
		<member firstname="Anastasia" lastname="Strutinska" country="UKR" />
	</team>
	<team id="37" score="16" time="8:08:25" penalty="0" gender="women" age="open" name="Anki">
		<member firstname="Anna" lastname="Slizkova" country="UKR" />
		<member firstname="Anna" lastname="Ivanova" country="UKR" />
	</team>
	<team id="38" score="11" time="5:54:09" penalty="0" gender="women" age="open" name="Kharkiv-3">
		<member firstname="Maria" lastname="Kobzeva" country="UKR" />
		<member firstname="Natalia" lastname="Stepanyanc" country="UKR" />
	</team>
</results>
